---
- hosts: dbservers
  become: yes
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true

    - name: Installing Mysql  and dependencies
      apt:
       name:
        - mysql-server
        - mysql-client 
        - python3-mysqldb
        - libmysqlclient-dev
       state: present
       update_cache: true

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: true

    - name: creating mysql user
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating database
      mysql_db:
        name: "{{db_name}}"
        state: present

    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted