---
- hosts: dbservers
  become: yes
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true

    - name: Download MySQL installer
      command: wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb

    
    # - name: Download MySQL Repo using get_url
    #   get_url:
    #     url: https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb
    #     dest: mysql-apt-config_0.8.29-1_all.deb
    #     mode: 0755
    #     group: admin
    #     owner: admin
    #     timeout: 20
    
    # - name: Install MySQL server & client
    #   shell: apt install -y ./mysql-apt-config_0.8.29-1_all.deb

    # - name: Update and upgrade apt packages
    #   apt:
    #     upgrade: yes
    #     update_cache: true

    # - name: Installing Mysql
    #   apt:
    #    name:
    #     - mysql-server
        
    - name: Installing mysql-related dependencies
      apt:
       name:
        - python3-mysqldb
        - libmysqlclient-dev
       state: present
       update_cache: true

    # - name: start and enable mysql service
    #   service:
    #     name: mysql
    #     state: started
    #     enabled: true

    # - name: creating mysql user
    #   mysql_user:
    #     name: "{{db_user}}"
    #     password: "{{db_pass}}"
    #     login_user: root
    #     login_password: "{{db_pass}}"
    #     priv: '*.*:ALL'
    #     state: present

    # - name: creating database
    #   mysql_db:
    #     name: "{{db_name}}"
    #     login_user: root
    #     login_password: "{{db_pass}}"
    #     state: present

    # - name: Enable remote login to mysql
    #   lineinfile:
    #      path: /etc/mysql/mysql.conf.d/mysqld.cnf
    #      regexp: '^bind-address'
    #      line: 'bind-address = 0.0.0.0'
    #      backup: yes
    #   notify:
    #      - Restart mysql

    # # Copy database dump file to remote host and restore it to database 'my_db'
    # - name: Copy database dump file
    #   copy:
    #     src: usable-prod-db.sql
    #     dest: /tmp

    # - name: >
    #     Import dump.sql with specific latin1 encoding,
    #     similar to mysql -u <username> --default-character-set=latin1 -p <password> < dump.sql
    #   community.mysql.mysql_db:
    #     state: import
    #     name: all
    #     encoding: latin1
    #     target: /tmp/usable-prod-db.sql
  
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted