---
- hosts: webservers
  become: yes
  vars_files:
    - ../vars/vars.yml
  vars:
    USER: admin
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true

    - name : Install Git
      apt:
        name: 
          - git
        state: latest

    # - name : Install Redis-cli
    #   apt:
    #     name: 
    #       - redis-cli
    #     state: latest

    - name : Download Node{{node_version}} & install
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{node_version}}.x | sudo -E bash -
        apt-get install nodejs -y

    - name : Install rsync
      apt:
        name: 
          - rsync
        state: latest

    # - name : Install yarn
    #   apt:
    #     name: 
    #       - yarn={{yarn_version}}

    - name : Install docker
      apt:
        name: 
          - docker
        state: latest

    - name: Install php related packages
      apt:
        name:
          - php{{php_version}}
          - php{{php_version}}-mysql
          - php{{php_version}}-pdo
          - php{{php_version}}-pdo-mysql
          - php{{php_version}}-xml
          - php{{php_version}}-gd
          - php{{php_version}}-curl
          - php{{php_version}}-zip
          - php{{php_version}}-imagick
        state: present

    - name: Install apache2-related libraries
      apt: 
        name: 
          - libapache2-mod-php
          - libapache2-mod-wsgi-py3
        state: latest

    - name: Install low-level utilities
      apt:
        name:
          - zip
          - unzip
        state: present

    - name: Install Angular
      command: npm install -g @angular/cli@{{angular_version_major}}

    - name : Install Gulp
      command: npm install -g gulp-cli@{{gulp_version}}

    - name : Install Bower
      command: npm install -g bower@{{bower_version}}
    
    - name: Enable rewrite module
      shell: a2enmod rewrite

    - name: Download Composer
      script: ../scripts/install-composer.sh

    - name: Move Composer globally
      command: mv composer.phar /usr/local/bin/composer

    - name: Set permissions on Composer
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    - name: Set environment variable
      shell: export SYMFONY_ENV=prod