---
- hosts: webservers
  user: admin
  become: yes
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Set up Apache virtualHost
      template:
        src: "../apache-conf/apache2.conf"
        dest: "/etc/apache2/sites-available/app.preprod.webforfashion.com.conf"

    - name: Copy conf 
      template:
        src: "../apache-conf/apache-999-oxalide.conf"
        dest: "/etc/apache2/conf-available/999-oxalide.conf"

    - name: Copy .htaccess file to server
      template:
        src: ../templates/v1.htaccess
        dest: "{{ CRM_MAIN_DIR }}/v1.htaccess"