---
- name: Create dest folder
  hosts: all
  user: admin
  become: yes
  vars:
    dest: "/var/www/site/"
  tasks:

    - name: create directory for website
      file:
        path: /var/www/site/
        state: directory
        mode: 0755