---
- hosts: webservers
  user: admin
  become: true
  vars_files:
    - ./vars/vars.yml
  vars:
    USER: admin

  tasks:
    - name : Install Git
      apt:
        name: 
          - git 
        state: latest
        update_cache: yes

    - name : Install NodeJs & npm
      apt:
        name: 
          - nodejs=20.18.1
          - npm=10.8.2
        state: present
        update_cache: yes

    - name : Install rsync
      apt:
        name: 
          - rsync
        state: latest
        update_cache: yes

    - name : Install Gulp
      apt:
        name: 
          - gulp=3.0.0
        state: present
        update_cache: yes

    - name : Install Bower
      apt:
        name: 
          - bower=1.8.14
        state: present
        update_cache: yes

    - name : Install Yarn
      apt:
        name: 
          - yarn=1.22.22
        state: present
        update_cache: yes

    - name : Install docker
      apt:
        name: 
          - docker
        state: latest
        update_cache: yes

    - name: Install php related packages
      apt:
        name:
          - php{{php_version}}
          - php{{php_version}}-mysql
          - php{{php_version}}-pdo
          - php{{php_version}}-pdo-mysql
          - php{{php_version}}-xml
          - php{{php_version}}-gd
          - php{{php_version}}-curl
          - php{{php_version}}-zip
        state: present
        update_cache: yes

    - name: Install apache-related pkgs
      apt: 
        name: 
          - libapache2-mod-php
          - libapache2-mod-wsgi-py3
        state: latest
        update_cache: yes

    - name: Install Angular
      shell:
        "npm install -g @angular/cli@16"

    - name: Install low-level utilities
      apt:
        name:
          - zip
          - unzip
    
    - name: Download Composer
      script: scripts/install-composer.sh

    - name: Move Composer globally
      command: "mv composer.phar /usr/local/bin/composer"

    - name: Set permissions on Composer
      file:
        path: /usr/local/bin/composer
        mode: "a+x"