---
# Installation de MySQL 8.0 sous Debian

- hosts: dbservers

  vars:
    debian_name: buster
    mysql_version: 8.0
    gpg_key_id: "A4A9406876FCBD3C456770C88C718D3B5072E1F5"
    source_directory: /root/playbooks/mysql_install_8.0
    root_password: "@Root6789P@ssw0rd@"

  user: admin

  tasks:

  - name: install gnupg linux package
    apt:
      name: gnupg

  - name: copy GPG key file
    copy:
      src: "{{ source_directory }}/mysql_pubkey.asc"
      dest: /tmp/mysql_pubkey.asc

  - name: install key
    apt_key:
      id: "{{ gpg_key_id }}"
      file: /tmp/mysql_pubkey.asc
      state: present

  - name: copy apt repository file
    template:
      src: "{{ source_directory }}/mysql.list"
      dest: /etc/apt/sources.list.d/mysql.list

  - name: configure package installation ... root password
    debconf:
      name: mysql-community-server
      question: mysql-community-server/root-pass
      value: "{{ root_password }}"
      vtype: password

  - name: configure package installation ... confirm root password
    debconf:
      name: mysql-community-server
      question: mysql-community-server/re-root-pass
      value: "{{ root_password }}"
      vtype: password

  - name: configure package installation ... authentication method
    debconf:
      name: mysql-community-server
      question: mysql-server/default-auth-override
      value: Use Strong Password Encryption (RECOMMENDED)
      vtype: select

  - name: install mysql
    apt:
      name: mysql-server
      update_cache: yes
    environment:
      DEBIAN_FRONTEND: noninteractive