- name: Initialize Server
  hosts: webservers
  user: admin
  become: true
  vars_files:
    - ./vars/vars.yml
  vars:
    MAIN_DIR: space/www/testing.eroolaconsulting.com/data/
    DOCUMENT_ROOT_DIR: space/www/testing.eroolaconsulting.com/data/current/web/
    RELEASE_DIR: space/www/testing.eroolaconsulting.com/data/releases
    LOG_DIR: space/logs/apache/testing.eroolaconsulting.com
    USER: admin

  tasks:
    - name : install dependencies before starting
      apt:
        name: 
          - nodejs
          - npm
          - git 
          - rsync
          - docker
        state: latest
        update_cache: yes

    - name: install php related packages
      apt:
        name:
          - php{{php_version}}
          - php{{php_version}}-mysql
          - php{{php_version}}-xml
          - php{{php_version}}-gd
          - php{{php_version}}-curl
        state: fixed
        update_cache: yes

    - name: Install other php-apache pkgs
      shell:
        "sudo apt install libapache2-mod-php libapache2-mod-wsgi-py3 -y"

    - name: Install Angular
      shell:
        "npm list -g @angular/cli || npm install -g @angular/cli"

    - name: Install low-level utilities
      apt:
        name: "{{ item }}"
      with_items:
        - zip
        - unzip
    
    - name: Download Composer
      script: scripts/install-composer.sh

    - name: Move Composer globally
      command: "mv composer.phar /usr/local/bin/composer"

    - name: Set permissions on Composer
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    # - name: Install Composer
    #   shell: |
    #     curl -sS https://getcomposer.org/installer -o composer-setup.php
    #     sudo php composer-setup.php --install-dir=/usr/bin --filename=composer
    #     sudo php composer-setup.php --install-dir=/usr/local/composer --filename=phpcomposer
    #     echo 'export PATH="$PATH:/usr/local/composer"' >> ~/.bashrc

    - name: Create directories if not exist
      file: 
        path: "{{ item }}"
        state: directory
        owner: admin
        group: admin
        mode: 0755
      loop:
        - "{{ MAIN_DIR }}"
        - "{{ DOCUMENT_ROOT_DIR }}"
        - "{{ RELEASE_DIR }}"
        - "{{ LOG_DIR }}"
    
    - name: Set up Apache virtuahHost
      template:
        src: "apache-conf/apache2.conf"
        dest: "/etc/apache2/sites-available/testing.eroolaconsulting.com"

    - name: create index file port 80 
      copy:
        content: "Hello world"
        dest: "{{ DOCUMENT_ROOT_DIR }}/index.html"