- name: Initialize Server
  hosts: webservers
  user: admin
  become: yes
  vars:
    DEST_DIR: space/www/testing.eroolaconsulting.com/data/current/web/
    LOG_DIR: space/logs/apache/testing.eroolaconsulting.com/php
    USER: admin
  tasks:
    - include_vars:
        file: vars.yml
    - name : install dependencies before starting
      apt:
        name: 
          - nodejs
          - npm
          - git
          - php
          - rsync
          - docker
        state: latest
        update_cache: yes
          
    - name: Install Angular
      shell:
        "npm install -g @angular/cli"

    - name: Install Composer
      shell: |
        curl -sS https://getcomposer.org/installer -o composer-setup.php
        sudo php composer-setup.php --install-dir=/usr/bin --filename=composer
        sudo php composer-setup.php --install-dir=/usr/local/composer --filename=phpcomposer
        echo 'export PATH="$PATH:/usr/local/composer"' >> ~/.bashrc

    - name: Create document root if not exists
      file: 
        path: "{{ item }}"
        state: directory
        owner: admin
        group: admin
        mode: 0755
      loop:
        - "{{ DEST_DIR }}"
        - "{{ LOG_DIR }}"
    
    - name: Set up Apache virtuahHost
      template:
        src: "apache-conf/apache2.conf"
        dest: "/etc/apache2/sites-available/testing.eroolaconsulting.com"

    - name: create index file port 80 
      copy:
        content: "Hello wolrd"
        dest: "{{ DEST_DIR }}/index.html"