---
- hosts: webservers
  user: admin
  become: true
  tasks:
    - name: Enable some apache2 modules
      command: /usr/sbin/a2enmod rewrite headers deflate expires

    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
