---
- hosts: dbservers
  become: yes
  vars_files:
    - ../../vars/vars.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true

    - name: Download MySQL installer
      command: wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb

    
    # - name: Download MySQL Repo using get_url
    #   get_url:
    #     url: https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb
    #     dest: mysql-apt-config_0.8.29-1_all.deb
    #     mode: 0755
    #     group: admin
    #     owner: admin
    #     timeout: 20
    
    # - name: Install MySQL server & client
    #   shell: apt install -y ./mysql-apt-config_0.8.29-1_all.deb

    # - name: Update and upgrade apt packages
    #   apt:
    #     upgrade: yes
    #     update_cache: true

    # - name: Installing Mysql
    #   apt:
    #    name:
    #     - mysql-server
        
    - name: Installing mysql-related dependencies
      apt:
       name:
        - python3-mysqldb
        - libmysqlclient-dev
       state: present
       update_cache: true

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: true