---
- hosts: dbservers
  become: yes
  vars_files:
    - ../../vars/vars.yml
  tasks:
    # Copy database dump file to remote host and restore it to database 'my_db'
    - name: Copy database dump file
      copy:
        src: ../../Dump20250224.sql
        dest: /tmp

    - name: >
        Import dump.sql with specific utf8 encoding,
      community.mysql.mysql_db:
        state: import
        name: all
        encoding: utf8
        target: /tmp/Dump20250224.sql