---
- hosts: all
  user: admin
  become: yes
  vars:
    dest: "/var/www/site"
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://yadechi@bitbucket.org/yadechi/symfony-demo-app.git
    ansistrano_git_branch: main
    ansistrano_deploy_to: "{{ dest }}"
    ansistrano_keep_releases: 3

  roles:
     - { role: ansistrano.deploy }