---
- name: Disable default Apache site
  become: true
  shell: /usr/sbin/a2dissite 000-default.conf

- name: Reload Apache
  become: true
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  become: true
  service:
    name: apache2
    state: restarted

- name: Enable new website
  become: true
  command: /usr/sbin/a2ensite app-preprod2.webforfashion.com.conf

- name: Reload Apache
  become: true
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  become: true
  service:
    name: apache2
    state: restarted

- name: Install NPM dependencies
  shell: "npm install"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/"
    
- name: Install Composer dependencies
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
    no_dev: false
    optimize_autoloader: false
  environment:
    COMPOSER_NO_INTERACTION: "1"   
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Build project
  shell: "gulp build"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/"

#TODO remove this & find clean way to do it
# - name: Replace Redis DNS by preprod values
#   become: true
#   shell: "sed -i 's,tcp://127.0.0.1:6379,tcp://sessionsredis-pp-1.jbfxlr.ng.0001.euw1.cache.amazonaws.com,g' {{ ansistrano_release_path.stdout }}/.env"

# - name: Replace assets url by preprod values
#   become: true
#   shell: "sed -i 's,ASSETS_URL=http://127.0.0.1:8881,ASSETS_URL=http://app-preprod2.webforfashion.com,g' {{ ansistrano_release_path.stdout }}/.env"

# - name: Replace url in index.html
#   become: true
#   shell: "sed -i 's,127.0.0.1:8881,app-preprod2.webforfashion.com,g' {{ ansistrano_release_path.stdout }}/templates/Core/Angular/index.html.twig"
# - name: Clear the cache
#   become: true
#   command: "{{ release_console_path }} cache:clear --no-warmup --env=prod"

# - name: Warm up the cache
#   become: true
#   command: "{{ release_console_path }} cache:warmup --env=prod"

# - name: Set up directory permissions for var
#   become: true
#   file:
#     path: "{{ release_var_path }}"
#     state: directory
#     mode: 0777
#     recurse: true