---
- name: Disable default Apache site
  become: true
  shell: /usr/sbin/a2dissite 000-default.conf

- name: Reload Apache
  become: true
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  become: true
  service:
    name: apache2
    state: restarted

- name: Enable new website
  become: true
  command: /usr/sbin/a2ensite testing.eroolaconsulting.com.conf

- name: Reload Apache
  become: true
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  become: true
  service:
    name: apache2
    state: restarted

- name: Install NPM dependencies
  shell: "npm install"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/"
    
- name: Install Composer dependencies
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
    no_dev: true
    optimize_autoloader: true
  environment:
    COMPOSER_NO_INTERACTION: "1"   
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Clear the cache
  become: true
  command: "{{ release_console_path }} cache:clear --no-warmup --env=prod"

- name: Warm up the cache
  become: true
  command: "{{ release_console_path }} cache:warmup --env=prod"

# - name: Set up directory permissions for var
#   become: true
#   file:
#     path: "{{ release_var_path }}"
#     state: directory
#     mode: 0777
#     recurse: true