---
- name: Set up Apache virtuahHost
  template:
    src: "temp/v1.htaccess"
    dest: "{{ ansistrano_release_path.stdout }}/.htaccess"
# - name: Install Composer dependencies
#   become: true
#   composer:
#     command: install
#     working_dir: "{{ ansistrano_release_path.stdout }}"

# - name: Clear the cache
#   become: true
#   command: "{{ release_console_path }} cache:clear --no-warmup --env=prod"

# - name: Warm up the cache
#   become: true
#   command: "{{ release_console_path }} cache:warmup --env=prod"

# - name: Set up directory permissions for var
#   become: true
#   file:
#     path: "{{ release_var_path }}"
#     state: directory
#     mode: 0777
#     recurse: true