---
  become: true
  tasks:
    - name: Set up Apache virtuahHost
      template:
        src: "temp/v1.htaccess"
        dest: space/www/testing.eroolaconsulting.com/data/current/public/.htaccess

    - name: Enable new website
      command: /usr/sbin/a2ensite testing.eroolaconsulting.com.conf
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache
 
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
# - name: Install Composer dependencies
#   become: true
#   composer:
#     command: install
#     working_dir: "{{ ansistrano_release_path.stdout }}"

# - name: Clear the cache
#   become: true
#   command: "{{ release_console_path }} cache:clear --no-warmup --env=prod"

# - name: Warm up the cache
#   become: true
#   command: "{{ release_console_path }} cache:warmup --env=prod"

# - name: Set up directory permissions for var
#   become: true
#   file:
#     path: "{{ release_var_path }}"
#     state: directory
#     mode: 0777
#     recurse: true