---
- name: Reload Apache
  become: true
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  become: true
  service:
    name: apache2
    state: restarted
    
- name: Install Composer dependencies
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
    no_dev: false
    optimize_autoloader: false
  environment:
    COMPOSER_NO_INTERACTION: "1"   
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Clear the cache
  become: true
  command: "php bin/console cache:clear --no-warmup --env=prod"

- name: Warm up the cache
  become: true
  command: "php bin/console cache:warmup --env=prod"

- name: Install NPM dependencies
  shell: "npm install"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/"